from experience_manager import ExperienceManager

em = ExperienceManager(state_file = "initial_state.json", \
        scene_file = "scenes.json", plot_file = "plot.json", players_file= "players_data.json")

em.set_player_role(0, 'Red')
em.set_player_role(1, 'Wolf')
print(em.get_first_scene(0))
print(em.get_first_scene(1))
#print(em.validate_choices('Wolf1', 'Mushroom'))
#em.apply_choice_postconditions("Wolf1", "Mushroom", "Eat")
# print(em.get_next_scene(0))
#print(em.get_next_scene(1))
print(em.get_next_scene(0))
em.apply_choice_postconditions("Red-Decides-Restaurant", "Restaurant", "Open")
#print(em.get_next_scene(0))
print(em.get_next_scene(1))
#print(em.get_next_scene(0))
#print(em.get_next_scene(1))
#print(em.get_next_scene(0))
#print(em.get_next_scene(1))
#print(em.validate_choices('Red-Decides-Restaurant', 'Restaurant'))
#em.apply_choice_postconditions("Red-Decides-Restaurant", "Restaurant", "Close")
#print(em.get_next_scene(1))

#em.apply_choice_postconditions("Red-Decides-Restaurant", "Restaurant", "Close")
#print(em.get_next_scene(1))
#em.apply_choice_postconditions("Wolf-Climbs-Tree", "Eat", "Bananas")
#print(em.get_next_scene(1))
#print(em.get_next_scene(1))
#print('\nFor Plot:', em.gamestate.plot['progression'])
#print("Wolf scenes:", em.gamestate.players[1].get_scenes(), '\n')